version: 2
updates:
  - package-ecosystem: cargo
    directory: /apps/server
    schedule:
      interval: weekly
    labels:
      - dependencies
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
    open-pull-requests-limit: 10

  - package-ecosystem: pub
    directory: /apps/client
    schedule:
      interval: weekly
    labels:
      - dependencies
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
    open-pull-requests-limit: 10
